meta:
  engine: 4.1.0
# U is a predefined unit of measure that means 19.05mm, which is MX spacing (u is 19.00mm)
points:
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        mcone:
          key.column_net: COL1
        mctwo:
          key.column_net: COL2
        mcthree:
          key.stagger: 0.25U
          key.column_net: COL3
        mcfour:
          key.stagger: 0.125U
          key.column_net: COL4
        mcfive:
          key.stagger: -0.125U
          key.column_net: COL5
        mcsix:
          key.stagger: -0.125U
          key.column_net: COL6
      rows:
        mrone:
          padding: U
          row_net: ROW2
        mrtwo:
          padding: U
          row_net: ROW3
        mrthree:
          padding: U
          row_net: ROW4
        mrfour:
          padding: U
          row_net: ROW5
    inner:
      anchor.shift: [50+6u,-100]
      columns:
        icone:
          key.stagger: 0.625U
          key.column_net: COL7
      rows:
        irone:
          padding: U
          row_net: ROW3
        irtwo:
          padding: U
          row_net: ROW4
        irthree:
          padding: U
          row_net: ROW5
    lower:
      anchor.shift: [50, -100-U]
      columns:
        lcone:
          key.column_net: COL1
        lctwo:
          key.column_net: COL2
        lcthree:
          key.stagger: 0.25U
          key.column_net: COL3
        lcfour:
          key.stagger: 0.125U
          key.column_net: COL4
      rows:
        lrone:
          padding: U
          row_net: ROW1
    thumb:
      anchor:
        ref: matrix_mcsix_mrone
        shift: [-0.4U, -1.2U]
        rotate: -30
      columns:
        tcone:
          key.column_net: COL5
        tctwo:
          key.stagger: 0.5U
          key.width: 2U
          key.rotate: 90
          key.column_net: COL6
      rows:
        trone:
          padding: U
          row_net: ROW1
    thumbOuter:
      anchor:
        ref: thumb_tcone_trone
        shift: [2U,0]
      columns:
        tOcone:
          key.column_net: COL7
      rows:
        tOrone:
          padding: U
          row_net: ROW1
        tOrtwo:
          padding: U
          row_net: ROW2
  mirror:
    ref: matrix_mcone_mrone
    distance: 300
outlines:
  board_left:
    - what: polygon
      operation: stack
      points:
      - ref: lower_lcone_lrone
        shift: [-0.5U-2,-0.5U-2]
      - ref: matrix_mcone_mrfour
        shift: [-0.5U-2,0.5U+2]
      - ref: matrix_mcfour_mrfour
        shift: [-0.5U-2,0.5U+3.3]
      - ref: matrix_mcfour_mrfour
        shift: [0.5U+2,0.5U+3.3]
      - ref: matrix_mcsix_mrfour
        shift: [0.5U+2,0.5U+2]
      - ref: inner_icone_irthree
        shift: [5, 0.5U+2]
      - ref: inner_icone_irthree
        shift: [1.3U, 0.5U+2]
      - ref: inner_icone_irthree
        shift: [1.5U+3, 0.3U]
      - ref: inner_icone_irthree
        shift: [1.5U+3, -3.6U]
      - ref: thumbOuter_tOcone_tOrone
        shift: [0.5U+2, -0.5U-2]
      - ref: lower_lcone_lrone
        shift: [4U+5.5,-0.5U-2]
      fillet: 2.5
  screw_holes_left:
    - what: circle
      radius: 1.1
      where: lower_lcone_lrone
      adjust:
        shift: [0.5U,0.5U]
    - what: circle
      radius: 1.1
      where: matrix_mcone_mrthree
      adjust:
        shift: [0.5U,0.5U]
    - what: circle
      radius: 1.1
      where: matrix_mcthree_mrfour
      adjust:
        shift: [0.3U,0.55U]
    - what: circle
      radius: 1.1
      where: matrix_mcthree_mrtwo
      adjust:
        shift: [0.5U-0.5,0.5U]
    - what: circle
      radius: 1.1
      where: lower_lcthree_lrone
      adjust:
        shift: [0.5U-0.5,0.5U]
    - what: circle
      radius: 1.1
      where: matrix_mcsix_mrfour
      adjust:
        shift: [0.7U,0.1U]
    - what: circle
      radius: 1.1
      where: thumb_tctwo_trone
      adjust:
        shift: [0.1U,0.6U]
  thru_holes_left:
    - what: outline
      name: screw_holes_left
      expand: 1.4
  screw_holes_cover:
    - what: circle
      radius: 1.1
      where: inner_icone_irthree
      adjust:
        shift: [1.25U,0.3U]
    - what: circle
      radius: 1.1
      where: inner_icone_irone
      adjust:
        shift: [0.8U,-0.9U]
    - what: circle
      radius: 1.1
      where: inner_icone_irone
      adjust:
        shift: [1.4U,-1.25U]
  thru_holes_cover:
    - what: outline
      name: screw_holes_cover
      expand: 1.4
  baseplate_left:
    - what: outline
      name: board_left
    - what: polygon
      operation: subtract
      points:
      - ref: inner_icone_irthree
        shift: [0.5U+2,0.5U+2]
      - ref: inner_icone_irthree
        shift: [0.5U+2,-3U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,-3.9U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,0.5U+2]
      fillet: 2
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [14.5, 14]
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [14.5, 5.5]
      adjust:
        shift: [1.9,3]
    - what: rectangle
      operation: subtract
      where: thumb_tctwo_trone
      size: [1.8U,U-6.5]
    - what: outline
      name: screw_holes_left
      operation: subtract
  baseplate_right:
    - what: outline
      name: board_left
    - what: polygon
      operation: subtract
      points:
      - ref: inner_icone_irthree
        shift: [0.5U+2,0.5U+2]
      - ref: inner_icone_irthree
        shift: [0.5U+2,-3U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,-3.9U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,0.5U+2]
      fillet: 2
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [14.5, 14]
    - what: rectangle
      operation: subtract
      where: thumb_tctwo_trone
      size: [1.8U,U-6.5]
    - what: outline
      name: screw_holes_left
      operation: subtract
  coverplate_both:
    - what: outline
      name: board_left
    - what: polygon
      operation: intersect
      points:
      - ref: inner_icone_irthree
        shift: [0.5U+2,0.5U+2]
      - ref: inner_icone_irthree
        shift: [0.5U+2,-3U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,-3.9U-1]
      - ref: inner_icone_irthree
        shift: [2U+2,0.5U+2]
      fillet: 2
    - what: outline
      name: screw_holes_cover
      operation: subtract
  backplate_1left:
    - what: outline
      name: board_left
    - what: outline
      name: thru_holes_cover
      operation: subtract
    - what: outline
      name: thru_holes_left
      operation: subtract
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [17, 10]
      adjust:
        shift: [-1.25,-2.4]
  backplate_1right:
    - what: outline
      name: board_left
    - what: outline
      name: thru_holes_cover
      operation: subtract
    - what: outline
      name: thru_holes_left
      operation: subtract
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [17, 10]
      adjust:
        shift: [1.25,-2.4]
    - what: rectangle
      operation: subtract
      where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
      size: [2, 5.5]
      adjust:
        shift: [8,3]
  backplate_2both:
    - what: outline
      name: board_left
    - what: outline
      name: screw_holes_cover
      operation: subtract
    - what: outline
      name: screw_holes_left
      operation: subtract
  backplate_3both:
    - what: outline
      name: board_left
    - what: polygon
      operation: subtract
      points:
      - ref: matrix_mcone_mrthree
        shift: [-1.5U, 0]
      - ref: matrix_mcone_mrthree
        shift: [8U, 0]
      - ref: matrix_mcone_mrthree
        shift: [8U, -5U]
      - ref: matrix_mcone_mrthree
        shift: [-1.5U, -5U]
      fillet: 2
    - what: outline
      name: screw_holes_cover
      operation: subtract
    - what: outline
      name: screw_holes_left
      operation: subtract
pcbs:
  slimdash:
    outlines:
      main:
        outline: board_left
      mount_hole:
        outline: thru_holes_left
      plate_mount_hole:
        outline: thru_holes_cover
      # Following Dwgs/Cmts are for layout debugging
      baseplate_left:
        outline: baseplate_left
        layer: "Cmts.User"
      backplate_1left:
        outline: backplate_1left
        layer: "Dwgs.User"
      backplate_1right:
        outline: backplate_1right
        layer: "Dwgs.User"
    footprints:
      choc_hotswap:
        what: choc
        where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: 180
      diode:
        what: diode
        where: /^(matrix|inner|lower|thumb|thumbOuter)_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [8,3]
          rotate: 270
